# Generated by Django 3.0.7 on 2020-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0002_auto_20200610_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_link_id',
            field=models.SlugField(default='adfg', max_length=20, verbose_name='id от видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_link_id',
            field=models.SlugField(default='asdfg', max_length=20, verbose_name='id от видео'),
            preserve_default=False,
        ),
    ]
