# Generated by Django 3.0.3 on 2020-07-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0004_course_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование файла')),
                ('file', models.FileField(null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurstar.Lesson')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалдар',
            },
        ),
    ]
