# Generated by Django 3.0.3 on 2020-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0005_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='file',
            field=models.FileField(null=True, upload_to='lesson_materials/'),
        ),
    ]
