# Generated by Django 3.0.3 on 2020-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0006_auto_20200712_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
