# Generated by Django 3.0.3 on 2020-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0009_auto_20200715_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='passed',
            name='lesson_number',
            field=models.IntegerField(default=0, verbose_name='Номер урока'),
        ),
    ]
