# Generated by Django 3.0.3 on 2020-08-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0010_passed_lesson_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=200, verbose_name='e-mail')),
                ('called', models.BooleanField(verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
    ]
