# Generated by Django 3.0.3 on 2020-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0011_callbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Отображаеться'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Отображаеться'),
        ),
        migrations.AddField(
            model_name='materials',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Отображаеться'),
        ),
        migrations.AlterField(
            model_name='callbacks',
            name='called',
            field=models.BooleanField(default=True, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube_link_id',
            field=models.SlugField(blank=True, max_length=20, verbose_name='id от видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_link_id',
            field=models.SlugField(blank=True, max_length=20, verbose_name='id от видео'),
        ),
    ]
