# Generated by Django 3.0.3 on 2020-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0013_auto_20200810_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacks',
            name='comment',
            field=models.CharField(default='Клиент не оставил коментарий', max_length=500, verbose_name='Комментарий'),
        ),
    ]
