# Generated by Django 3.0.3 on 2020-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurstar', '0014_callbacks_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='KZ', max_length=20, verbose_name='Язык'),
        ),
    ]
